# Generated by Django 3.2.7 on 2021-09-05 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_address_zip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='zip',
        ),
    ]
